[package]
name = "imnodes-sys"
version = "0.1.0"
edition = "2021"
authors = ["Benedikt Mandelkow", "imnodes-rs contributors"]
description = "Raw FFI bindings to imnodes"
license = "MIT/Apache-2.0"
categories = ["gui", "external-ffi-bindings"]
build = "build.rs"
links = "imnodes"
rust-version = "1.60.0"

[dependencies]
imgui-sys = "0.8.2"

[build-dependencies]
cc = "1.0.72"
